// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DSMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DSMath";
  readonly sourceName: "contracts/lib/DSMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea2646970667358221220db2b9096b71c35d1a532152dc4aa0186e9c6b0683f6552f1bee84391318267fe64736f6c63430008130033";
  readonly deployedBytecode: "0x600080fdfea2646970667358221220db2b9096b71c35d1a532152dc4aa0186e9c6b0683f6552f1bee84391318267fe64736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/lib/DSMath.sol";
  readonly buildInfoId: "solc-0_8_19-ca295bb33ef6d8aae6ee552e4bc65300ba6358b9";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DSMath"]: DSMath$Type;
    ["contracts/lib/DSMath.sol:DSMath"]: DSMath$Type;
  }
}