// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MockFlapper$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockFlapper";
  readonly sourceName: "contracts/mocks/MockAuctions.sol";
  readonly abi: [{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"amount","type":"uint256"}],"name":"Caged","type":"event"},{"inputs":[{"internalType":"uint256","name":"amount","type":"uint256"}],"name":"cage","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x60808060405234601457609e908161001a8239f35b600080fdfe6080806040526004361015601257600080fd5b600090813560e01c63a2f91af214602857600080fd5b34606457602036600319011260645760207f78d0a0122ae8526aabfe855b93dae61d485d27de6ed864657206e95f9f2b367d916004358152a180f35b5080fdfea2646970667358221220cc73bfa413f0c35e00c014829c94a8714e6c9b56963e1e69b5bb3e5a83db755c64736f6c63430008130033";
  readonly deployedBytecode: "0x6080806040526004361015601257600080fd5b600090813560e01c63a2f91af214602857600080fd5b34606457602036600319011260645760207f78d0a0122ae8526aabfe855b93dae61d485d27de6ed864657206e95f9f2b367d916004358152a180f35b5080fdfea2646970667358221220cc73bfa413f0c35e00c014829c94a8714e6c9b56963e1e69b5bb3e5a83db755c64736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mocks/MockAuctions.sol";
  readonly buildInfoId: "solc-0_8_19-ca295bb33ef6d8aae6ee552e4bc65300ba6358b9";
};

export interface MockFlopper$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MockFlopper";
  readonly sourceName: "contracts/mocks/MockAuctions.sol";
  readonly abi: [{"anonymous":false,"inputs":[],"name":"Caged","type":"event"},{"inputs":[],"name":"cage","outputs":[],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x60808060405234601457608f908161001a8239f35b600080fdfe6004361015600c57600080fd5b6000803560e01c636924500914602157600080fd5b34605657806003193601126056577f61e85925245534783490ebf691a7a38d39e02f3c319a97cd5f713d88899d1f478180a180f35b80fdfea2646970667358221220c582a5d615fa3605a791a61a5b7b51f2b3ebb9053385425b07099290af3e2f9c64736f6c63430008130033";
  readonly deployedBytecode: "0x6004361015600c57600080fd5b6000803560e01c636924500914602157600080fd5b34605657806003193601126056577f61e85925245534783490ebf691a7a38d39e02f3c319a97cd5f713d88899d1f478180a180f35b80fdfea2646970667358221220c582a5d615fa3605a791a61a5b7b51f2b3ebb9053385425b07099290af3e2f9c64736f6c63430008130033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/mocks/MockAuctions.sol";
  readonly buildInfoId: "solc-0_8_19-ca295bb33ef6d8aae6ee552e4bc65300ba6358b9";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MockFlapper"]: MockFlapper$Type
    ["MockFlopper"]: MockFlopper$Type;
    ["contracts/mocks/MockAuctions.sol:MockFlapper"]: MockFlapper$Type
    ["contracts/mocks/MockAuctions.sol:MockFlopper"]: MockFlopper$Type;
  }
}