USDog Stablecoin Protocol: Calc.sol File Reference
Calc.sol File Reference
import "./lib/DSMath.sol";
Functions
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
constructor ()
function file (bytes32 what, uint256 data) external auth
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function mul (uint256 x, uint256 y) internal pure returns(uint256 z)
function price (uint256 top, uint256 dur) external view returns(uint256)
function rmul (uint256 x, uint256 y) internal pure returns(uint256 z)
function rpow (uint256 x, uint256 n) internal pure returns(uint256 z)
Variables
pragma solidity
contract LinearDecrease
modifier auth { require(wards[msg.sender] == 1, "LinearDecrease/not-authorized")
_
tau
contract StairstepExponentialDecrease
step
cut
uint256 constant RAY = 10 ** 27
contract ExponentialDecrease
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 33 of file Calc.sol.
Referenced by cash(), fess(), flap(), flog(), flop(), kick(), pack(), rdiv(), redo(), rmul(), rpow(), skim(), thaw(), wdiv(), and wmul().
constructor()
constructor ()
Definition at line 21 of file Calc.sol.
References tau.
deny()
function deny (address usr)
Definition at line 15 of file Calc.sol.
References usr.
file()
function file (bytes32 what, uint256 data)
Definition at line 27 of file Calc.sol.
References tau.
mapping()
mapping (address , uint256)
mul()
function mul (uint256 x, uint256 y)
Definition at line 39 of file Calc.sol.
Referenced by cage(), pack(), poke(), price(), rdiv(), rmul(), rpow(), wdiv(), and wmul().
price()
function price (uint256 top, uint256 dur)
Definition at line 44 of file Calc.sol.
References mul(), sub(), tau, and top.
rely()
function rely (address usr)
Definition at line 14 of file Calc.sol.
References usr.
rmul()
function rmul (uint256 x, uint256 y)
Definition at line 88 of file Calc.sol.
References DSMath, and RAY.
Referenced by cash(), flow(), kick(), redo(), rpow(), and skim().
rpow()
function rpow (uint256 x, uint256 n)
Definition at line 92 of file Calc.sol.
References RAY, and rmul().
sub()
function sub (uint256 x, uint256 y)
Definition at line 36 of file Calc.sol.
Referenced by flap(), flog(), flop(), flow(), heal(), kiss(), price(), skim(), status(), and take().
Variable Documentation
_
_
Definition at line 16 of file Calc.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "LinearDecrease/not-authorized")
Definition at line 16 of file Calc.sol.
cut
cut
Definition at line 64 of file Calc.sol.
ExponentialDecrease
contract ExponentialDecrease
Initial value:
{
    using DSMath for uint256
Definition at line 117 of file Calc.sol.
LinearDecrease
contract LinearDecrease
Initial value:
{
    using DSMath for uint256
Definition at line 9 of file Calc.sol.
RAY
uint256 constant RAY = 10 ** 27
Definition at line 86 of file Calc.sol.
Referenced by pack(), rmul(), rpow(), and useStablecoin().
solidity
pragma solidity
Definition at line 2 of file Calc.sol.
StairstepExponentialDecrease
contract StairstepExponentialDecrease
Initial value:
{
    using DSMath for uint256
Definition at line 53 of file Calc.sol.
step
step
Definition at line 63 of file Calc.sol.
Referenced by DocsPage().
tau
tau
Definition at line 19 of file Calc.sol.
Referenced by constructor(), file(), and price().