USDog Stablecoin Protocol: DSMath.sol File Reference
DSMath.sol File Reference
Functions
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function mul (uint256 x, uint256 y) internal pure returns(uint256 z)
function wmul (uint256 x, uint256 y) internal pure returns(uint256 z)
function wdiv (uint256 x, uint256 y) internal pure returns(uint256 z)
function rmul (uint256 x, uint256 y) internal pure returns(uint256 z)
function rdiv (uint256 x, uint256 y) internal pure returns(uint256 z)
function rpow (uint256 x, uint256 n) internal pure returns(uint256 z)
function radmul (uint256 x, uint256 y) internal pure returns(uint256 z)
function raddiv (uint256 x, uint256 y) internal pure returns(uint256 z)
function wadToRay (uint256 wad) internal pure returns(uint256 ray)
function rayToWad (uint256 ray) internal pure returns(uint256 wad)
function wadToRad (uint256 wad) internal pure returns(uint256 rad)
function rayToRad (uint256 ray) internal pure returns(uint256 rad)
function min (uint256 x, uint256 y) internal pure returns(uint256 z)
function max (uint256 x, uint256 y) internal pure returns(uint256 z)
Variables
pragma solidity
library DSMath
uint256 constant RAY = 10 ** 27
uint256 constant RAD = 10 ** 45
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 17 of file DSMath.sol.
Referenced by raddiv(), radmul(), rdiv(), rmul(), wdiv(), and wmul().
max()
function max (uint256 x, uint256 y)
Definition at line 104 of file DSMath.sol.
Referenced by burn(), DirectorySection(), take(), transferFrom(), transferFrom(), and useIsMobile().
min()
function min (uint256 x, uint256 y)
Definition at line 100 of file DSMath.sol.
mul()
function mul (uint256 x, uint256 y)
Definition at line 25 of file DSMath.sol.
Referenced by raddiv(), radmul(), rayToRad(), rdiv(), rmul(), wadToRad(), wadToRay(), wdiv(), and wmul().
raddiv()
function raddiv (uint256 x, uint256 y)
Definition at line 72 of file DSMath.sol.
References add(), mul(), and RAD.
radmul()
function radmul (uint256 x, uint256 y)
Definition at line 67 of file DSMath.sol.
References add(), mul(), and RAD.
rayToRad()
function rayToRad (uint256 ray)
Definition at line 94 of file DSMath.sol.
References mul().
rayToWad()
function rayToWad (uint256 ray)
Definition at line 84 of file DSMath.sol.
rdiv()
function rdiv (uint256 x, uint256 y)
Definition at line 47 of file DSMath.sol.
References add(), mul(), and RAY.
rmul()
function rmul (uint256 x, uint256 y)
Definition at line 42 of file DSMath.sol.
References add(), mul(), and RAY.
Referenced by rpow().
rpow()
function rpow (uint256 x, uint256 n)
Definition at line 52 of file DSMath.sol.
References RAY, and rmul().
sub()
function sub (uint256 x, uint256 y)
Definition at line 21 of file DSMath.sol.
wadToRad()
function wadToRad (uint256 wad)
Definition at line 89 of file DSMath.sol.
References mul().
wadToRay()
function wadToRay (uint256 wad)
Definition at line 79 of file DSMath.sol.
References mul().
wdiv()
function wdiv (uint256 x, uint256 y)
Definition at line 35 of file DSMath.sol.
References add(), mul(), and WAD.
wmul()
function wmul (uint256 x, uint256 y)
Definition at line 30 of file DSMath.sol.
References add(), mul(), and WAD.
Variable Documentation
DSMath
library DSMath
Initial value:
{
    uint256 constant WAD = 10 ** 18
Definition at line 10 of file DSMath.sol.
Referenced by bark(), cage(), cage(), constructor(), constructor(), DocsPage(), drip(), drip(), rdiv(), rmul(), wdiv(), and wmul().
RAD
uint256 constant RAD = 10 ** 45
Definition at line 13 of file DSMath.sol.
Referenced by raddiv(), and radmul().
RAY
uint256 constant RAY = 10 ** 27
Definition at line 12 of file DSMath.sol.
Referenced by rdiv(), rmul(), and rpow().
solidity
pragma solidity
Definition at line 2 of file DSMath.sol.