USDog Stablecoin Protocol: Dog.sol File Reference
Dog.sol File Reference
import "./lib/DSMath.sol";
Data Structures
struct Ilk
Functions
function urns (bytes32, address) external view returns(uint256
function grab (bytes32, address, address, address, int256, int256) external
function hope (address) external
function nope (address) external
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
struct Ilk mapping (bytes32=> Ilk) public ilks
event Bark (bytes32 indexed ilk, address indexed urn, uint256 ink, uint256 art, uint256 due, address clip, uint256 indexed id)
constructor (address vat_)
function min (uint256 x, uint256 y) internal pure returns(uint256 z)
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function mul (uint256 x, uint256 y) internal pure returns(uint256 z)
function file (bytes32 what, address data) external auth
function file (bytes32 what, uint256 data) external auth
function file (bytes32 ilk, bytes32 what, uint256 data) external auth
function file (bytes32 ilk, bytes32 what, address clip) external auth
function chop (bytes32 ilk) external view returns(uint256)
function cage () external auth
function bark (bytes32 ilk, address urn, address kpr) external returns(uint256 id)
function digs (bytes32 ilk, uint256 rad) external auth
function cage (bytes32 ilk) external auth
Variables
pragma solidity
function uint256
contract Dog
modifier auth { require(wards[msg.sender] == 1, "Dog/not-authorized")
_
ClipLike clip
uint256 chop
uint256 hole
uint256 dirt
vat
vow
live
Hole
Dirt
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 74 of file Dog.sol.
Referenced by bark().
bark()
function bark (bytes32 ilk, address urn, address kpr)
Definition at line 121 of file Dog.sol.
References add(), art, Bark(), Dirt, DSMath, Hole, ilk, ilks(), ink, live, min(), mul(), spot, sub(), tab, uint256, vat, and vow.
Bark()
event Bark (bytes32 indexed ilk, address indexed urn, uint256 ink, uint256 art, uint256 due, address clip, uint256 indexed id)
Referenced by bark().
cage() [1/2]
function cage ()
Definition at line 116 of file Dog.sol.
References live.
cage() [2/2]
function cage (bytes32 ilk)
Definition at line 166 of file Dog.sol.
References DSMath, ilk, and ilks().
chop()
function chop (bytes32 ilk)
Definition at line 112 of file Dog.sol.
References ilk, and ilks().
constructor()
constructor (address vat_)
Definition at line 64 of file Dog.sol.
References live, and vat.
deny()
function deny (address usr)
Definition at line 32 of file Dog.sol.
References usr.
digs()
function digs (bytes32 ilk, uint256 rad)
Definition at line 161 of file Dog.sol.
References dirt, Dirt, ilk, ilks(), and sub().
file() [1/4]
function file (bytes32 ilk, bytes32 what, address clip)
Definition at line 104 of file Dog.sol.
References clip, ilk, ilks(), and live.
file() [2/4]
function file (bytes32 ilk, bytes32 what, uint256 data)
Definition at line 97 of file Dog.sol.
References ilk, ilks(), and live.
file() [3/4]
function file (bytes32 what, address data)
Definition at line 85 of file Dog.sol.
References live, and vow.
file() [4/4]
function file (bytes32 what, uint256 data)
Definition at line 91 of file Dog.sol.
References Hole, and live.
grab()
function grab (bytes32 i, address u, address v, address w, int256 dink, int256 dart)
Definition at line 201 of file Vat.sol.
References _addInt(), _mulInt(), gem, ilk, ilks(), sin(), urns(), and vice.
hope()
function hope (address usr)
Definition at line 237 of file Vat.sol.
References usr.
mapping() [1/2]
mapping (address , uint256)
mapping() [2/2]
struct Ilk mapping (bytes32 , Ilk)
min()
function min (uint256 x, uint256 y)
Definition at line 71 of file Dog.sol.
Referenced by bark().
mul()
function mul (uint256 x, uint256 y)
Definition at line 80 of file Dog.sol.
Referenced by bark().
nope()
function nope (address usr)
Definition at line 238 of file Vat.sol.
References usr.
rely()
function rely (address usr)
Definition at line 31 of file Dog.sol.
References usr.
sub()
function sub (uint256 x, uint256 y)
Definition at line 77 of file Dog.sol.
Referenced by bark(), and digs().
urns()
function urns (bytes32 , address)
Referenced by DocsPage(), frob(), and grab().
Variable Documentation
_
_
Definition at line 33 of file Dog.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "Dog/not-authorized")
Definition at line 33 of file Dog.sol.
chop
uint256 chop
Definition at line 1 of file Dog.sol.
clip
ClipLike clip
Definition at line 0 of file Dog.sol.
Referenced by file().
dirt
uint256 dirt
Definition at line 3 of file Dog.sol.
Referenced by digs().
Dirt
Dirt
Definition at line 50 of file Dog.sol.
Referenced by bark(), and digs().
Dog
contract Dog
Initial value:
{
    using DSMath for uint256
Definition at line 26 of file Dog.sol.
Referenced by DocsPage().
hole
uint256 hole
Definition at line 2 of file Dog.sol.
Hole
Hole
Definition at line 49 of file Dog.sol.
Referenced by bark(), and file().
live
live
Definition at line 48 of file Dog.sol.
Referenced by bark(), cage(), constructor(), file(), file(), file(), and file().
solidity
pragma solidity
Definition at line 2 of file Dog.sol.
uint256
function uint256
Definition at line 8 of file Dog.sol.
Referenced by bark().
vat
vat
Definition at line 45 of file Dog.sol.
Referenced by bark(), and constructor().
vow
vow
Definition at line 46 of file Dog.sol.
Referenced by bark(), and file().