USDog Stablecoin Protocol: End.sol File Reference
End.sol File Reference
import "./lib/DSMath.sol";
Functions
function ilks (bytes32) external view returns(uint256
function urns (bytes32, address) external view returns(uint256
function move (address, address, uint256) external
function hope (address) external
function flux (bytes32, address, address, uint256) external
function grab (bytes32, address, address, address, int256, int256) external
function suck (address, address, uint256) external
function cage () external
function cage (bytes32) external
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
mapping (bytes32=> uint256) public tag
mapping (bytes32=> mapping(address=> uint256)) public out
event Cage ()
event Cage (bytes32 indexed ilk)
event Skip (bytes32 indexed ilk, uint256 indexed id)
event Skim (bytes32 indexed ilk, address indexed urn, uint256 wad, uint256 art)
event Free (bytes32 indexed ilk, address indexed usr, uint256 ink)
event Thaw ()
event Flow (bytes32 indexed ilk)
event Pack (address indexed usr, uint256 wad)
event Cash (bytes32 indexed ilk, address indexed usr, uint256 wad)
constructor ()
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function mul (uint256 x, uint256 y) internal pure returns(uint256 z)
function min (uint256 x, uint256 y) internal pure returns(uint256 z)
function rmul (uint256 x, uint256 y) internal pure returns(uint256 z)
function wdiv (uint256 x, uint256 y) internal pure returns(uint256 z)
function file (bytes32 what, address data) external auth
function file (bytes32 what, uint256 data) external auth
function skip (bytes32 ilk, uint256 id) external
function skim (bytes32 ilk, address urn) external
function free (bytes32 ilk) external
function thaw () external
function flow (bytes32 ilk) external
function pack (uint256 wad) external
function cash (bytes32 ilk, uint256 wad) external
Variables
pragma solidity
function uint256
contract End
modifier auth { require(wards[msg.sender] == 1, "End/not-authorized")
_
vat
dog
vow
jug
pot
spot
live
when
wait
debt
uint256 constant WAD = 10 ** 18
uint256 constant RAY = 10 ** 27
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 106 of file End.sol.
Cage() [1/2]
event Cage ()
Referenced by cage(), and cage().
cage() [1/2]
function cage ()
Definition at line 147 of file End.sol.
References Cage(), dog, jug, live, pot, spot, vat, vow, and when.
Cage() [2/2]
event Cage (bytes32 indexed ilk)
cage() [2/2]
function cage (bytes32 ilk)
Definition at line 161 of file End.sol.
References art, Cage(), ilk, live, mul(), spot, uint256, and vat.
cash()
function cash (bytes32 ilk, uint256 wad)
Definition at line 221 of file End.sol.
References add(), Cash(), ilk, rmul(), and vat.
Cash()
event Cash (bytes32 indexed ilk, address indexed usr, uint256 wad)
Referenced by cash().
constructor()
constructor ()
Definition at line 100 of file End.sol.
References live.
deny()
function deny (address usr)
Definition at line 64 of file End.sol.
References usr.
file() [1/2]
function file (bytes32 what, address data)
Definition at line 129 of file End.sol.
References dog, jug, live, pot, spot, vat, and vow.
file() [2/2]
function file (bytes32 what, uint256 data)
Definition at line 140 of file End.sol.
References live, and wait.
flow()
function flow (bytes32 ilk)
Definition at line 204 of file End.sol.
References debt, Flow(), ilk, rmul(), sub(), uint256, vat, and wdiv().
Flow()
event Flow (bytes32 indexed ilk)
Referenced by flow().
flux()
function flux (bytes32 ilk, address src, address dst, uint256 wad)
Definition at line 127 of file Vat.sol.
free()
function free (bytes32 ilk)
Definition at line 188 of file End.sol.
References Free(), ilk, ink, live, uint256, vat, and vow.
Free()
event Free (bytes32 indexed ilk, address indexed usr, uint256 ink)
Referenced by free().
grab()
function grab (bytes32 i, address u, address v, address w, int256 dink, int256 dart)
Definition at line 201 of file Vat.sol.
hope()
function hope (address usr)
Definition at line 237 of file Vat.sol.
ilks()
function ilks (bytes32)
mapping() [1/3]
mapping (address , uint256)
mapping() [2/3]
mapping (bytes32 , mapping(address=> uint256))
mapping() [3/3]
mapping (bytes32 , uint256)
min()
function min (uint256 x, uint256 y)
Definition at line 116 of file End.sol.
move()
function move (address src, address dst, uint256 rad)
Definition at line 133 of file Vat.sol.
References _add(), _sub(), dai, and wish().
Referenced by DocsPage().
mul()
function mul (uint256 x, uint256 y)
Definition at line 113 of file End.sol.
Pack()
event Pack (address indexed usr, uint256 wad)
Referenced by pack().
pack()
function pack (uint256 wad)
Definition at line 214 of file End.sol.
References add(), debt, mul(), Pack(), RAY, vat, and vow.
rely()
function rely (address usr)
Definition at line 63 of file End.sol.
References usr.
rmul()
function rmul (uint256 x, uint256 y)
Definition at line 121 of file End.sol.
References add(), mul(), and RAY.
skim()
function skim (bytes32 ilk, address urn)
Definition at line 176 of file End.sol.
References add(), art, ilk, ink, min(), rmul(), Skim(), sub(), uint256, vat, and vow.
Skim()
event Skim (bytes32 indexed ilk, address indexed urn, uint256 wad, uint256 art)
Referenced by skim().
skip()
function skip (bytes32 ilk, uint256 id)
Definition at line 170 of file End.sol.
References ilk, and Skip().
Skip()
event Skip (bytes32 indexed ilk, uint256 indexed id)
Referenced by skip().
sub()
function sub (uint256 x, uint256 y)
Definition at line 110 of file End.sol.
suck()
function suck (address u, address v, uint256 rad)
Definition at line 226 of file Vat.sol.
References _add(), dai, debt, sin(), and vice.
Thaw()
event Thaw ()
Referenced by thaw().
thaw()
function thaw ()
Definition at line 195 of file End.sol.
References add(), debt, live, Thaw(), vat, vow, wait, and when.
urns()
function urns (bytes32 , address)
wdiv()
function wdiv (uint256 x, uint256 y)
Definition at line 124 of file End.sol.
References add(), mul(), and WAD.
Variable Documentation
_
_
Definition at line 65 of file End.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "End/not-authorized")
Definition at line 65 of file End.sol.
debt
function debt
Definition at line 78 of file End.sol.
Referenced by DocsPage(), flow(), pack(), and thaw().
dog
dog
Definition at line 69 of file End.sol.
End
contract End
Initial value:
{
    using DSMath for uint256
Definition at line 58 of file End.sol.
Referenced by DocsPage().
jug
jug
Definition at line 71 of file End.sol.
Referenced by cage(), and file().
live
live
Definition at line 75 of file End.sol.
pot
pot
Definition at line 72 of file End.sol.
Referenced by cage(), and file().
RAY
uint256 constant RAY = 10 ** 27
Definition at line 120 of file End.sol.
solidity
pragma solidity
Definition at line 2 of file End.sol.
spot
spot
Definition at line 73 of file End.sol.
Referenced by bark(), cage(), cage(), DirectorySection(), DocsPage(), ErrorReporter(), file(), HomePage(), HoverReceiver(), kick(), Navigation(), OpenVaultInner(), OpenVaultPage(), poke(), RiskDisclaimer(), RootLayout(), StakePage(), useIsMobile(), useStablecoin(), and VaultsPage().
uint256
function uint256
Definition at line 8 of file End.sol.
vat
vat
Definition at line 68 of file End.sol.
vow
vow
Definition at line 70 of file End.sol.
WAD
uint256 constant WAD = 10 ** 18
Definition at line 119 of file End.sol.
Referenced by wdiv(), and wmul().
wait
wait
Definition at line 77 of file End.sol.
Referenced by file(), flog(), and thaw().
when
when
Definition at line 76 of file End.sol.
Referenced by cage(), DocsPage(), and thaw().