USDog Stablecoin Protocol: FlashLiquidator.sol File Reference
FlashLiquidator.sol File Reference
import "./lib/DSMath.sol";
Data Structures
struct FlashLoanData
Functions
function balanceOf (address account) external view returns(uint256)
function transfer (address recipient, uint256 amount) external returns(bool)
function allowance (address owner, address spender) external view returns(uint256)
function approve (address spender, uint256 amount) external returns(bool)
function transferFrom (address sender, address recipient, uint256 amount) external returns(bool)
function decimals () external view returns(uint8)
function dai (address) external view returns(uint256)
function exit (address, uint256) external
function gem () external view returns(address)
function swapExactTokensForTokens (uint256 amountIn, uint256 amountOutMin, address[] calldata path, address to, uint256 deadline) external returns(uint256[] memory amounts)
function token1 () external view returns(address)
function getReserves () external view returns(uint112 reserve0
function swap (uint amount0Out, uint amount1Out, address to, bytes calldata data) external
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
mapping (address=> bool) public supportedCollateral
mapping (address=> address) public collateralJoins
event FlashLiquidation (address indexed borrower, address indexed collateralToken, uint256 repayAmount, uint256 collateralReceived, uint256 profit)
event CollateralAdded (address indexed token, address indexed join)
event EmergencyWithdraw (address indexed token, uint256 amount)
constructor (address vat_, address daiJoin_)
function addCollateral (address token, address join) external auth
function removeCollateral (address token) external auth
function liquidateMemeCollateral (address borrower, address collateralVToken, address debtVToken, uint256 repayAmount, address flashLoanPool) external
function pancakeCall (address sender, uint256 amount0, uint256 amount1, bytes calldata data) external
function clipperCall (address sender, uint256 owe, uint256 slice, bytes calldata data) external
function executeClipperLiquidation (address borrower, address collateralToken, uint256 repayAmount) internal
function getWBNBForDAI (uint256 daiAmount) internal view returns(uint256)
function pairFor (address tokenA, address tokenB) internal pure returns(address pair)
function estimateLiquidationProfit (address borrower, address collateralVToken, address debtVToken, uint256 repayAmount) external view returns(uint256 estimatedProfit
function getCollateralHealthFactor (address borrower) external view returns(uint256)
function emergencyWithdraw (address token, uint256 amount) external auth
function emergencyWithdrawInternal (uint256 amount) external auth
function getFlashLoanState () external view returns(FlashLoanData memory)
Variables
pragma solidity
function uint112 reserve1
function uint112 uint32 blockTimestampLast
contract FlashLiquidator
modifier auth { require(wards[msg.sender] == 1, "FlashLiquidator/not-authorized")
_
immutable vat
immutable daiJoin
immutable dai
constant router = IPancakeRouter(0x10ED43C718714eb63d5aA57B78B54704E256024E)
constant WBNB = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
struct FlashLoanData flashLoanState
function bool isViable
Function Documentation
addCollateral()
function addCollateral (address token, address join)
Definition at line 112 of file FlashLiquidator.sol.
References CollateralAdded(), and join().
allowance()
function allowance (address owner, address spender)
Referenced by approve(), approve(), burn(), permit(), transferFrom(), and transferFrom().
approve()
function approve (address spender, uint256 amount)
Definition at line 59 of file MockToken.sol.
References allowance(), Approval(), and usr.
balanceOf()
function balanceOf (address account)
Referenced by burn(), constructor(), mint(), mint(), transferFrom(), and transferFrom().
clipperCall()
function clipperCall (address sender, uint256 owe, uint256 slice, bytes calldata data)
Definition at line 270 of file FlashLiquidator.sol.
References FlashLoanData::collateralJoin, FlashLoanData::collateralToken, dai, FlashLoanData::expectedCollateral, flashLoanState, FlashLoanData::inFlashLoan, router, uint256, and WBNB.
CollateralAdded()
event CollateralAdded (address indexed token, address indexed join)
Referenced by addCollateral().
constructor()
constructor (address vat_, address daiJoin_)
Definition at line 104 of file FlashLiquidator.sol.
References dai, daiJoin, and vat.
dai()
function dai (address)
decimals()
function decimals ()
Definition at line 12 of file MockToken.sol.
deny()
function deny (address usr)
Definition at line 63 of file FlashLiquidator.sol.
References usr.
EmergencyWithdraw()
event EmergencyWithdraw (address indexed token, uint256 amount)
Referenced by emergencyWithdraw().
emergencyWithdraw()
function emergencyWithdraw (address token, uint256 amount)
Definition at line 368 of file FlashLiquidator.sol.
References EmergencyWithdraw().
emergencyWithdrawInternal()
function emergencyWithdrawInternal (uint256 amount)
Definition at line 373 of file FlashLiquidator.sol.
References vat.
estimateLiquidationProfit()
function estimateLiquidationProfit (address borrower, address collateralVToken, address debtVToken, uint256 repayAmount)
executeClipperLiquidation()
function executeClipperLiquidation (address borrower, address collateralToken, uint256 repayAmount)
Definition at line 313 of file FlashLiquidator.sol.
Referenced by pancakeCall().
exit()
function exit (address usr, uint256 wad)
Definition at line 102 of file Join.sol.
References dai, dec, gem, ilk, live, ONE, uint256, usr, and vat.
FlashLiquidation()
event FlashLiquidation (address indexed borrower, address indexed collateralToken, uint256 repayAmount, uint256 collateralReceived, uint256 profit)
Referenced by pancakeCall().
gem()
function gem ()
Definition at line 36 of file Join.sol.
Referenced by constructor(), exit(), flux(), frob(), grab(), join(), and slip().
getCollateralHealthFactor()
function getCollateralHealthFactor (address borrower)
Definition at line 361 of file FlashLiquidator.sol.
getFlashLoanState()
function getFlashLoanState ()
Definition at line 378 of file FlashLiquidator.sol.
References flashLoanState.
getReserves()
function getReserves ()
getWBNBForDAI()
function getWBNBForDAI (uint256 daiAmount)
Definition at line 323 of file FlashLiquidator.sol.
References dai, router, uint256, and WBNB.
Referenced by liquidateMemeCollateral().
liquidateMemeCollateral()
function liquidateMemeCollateral (address borrower, address collateralVToken, address debtVToken, uint256 repayAmount, address flashLoanPool)
Definition at line 124 of file FlashLiquidator.sol.
References dai, flashLoanState, getWBNBForDAI(), FlashLoanData::inFlashLoan, token1(), uint256, and WBNB.
mapping() [1/3]
mapping (address , address)
mapping() [2/3]
mapping (address , bool)
mapping() [3/3]
mapping (address , uint256)
pairFor()
function pairFor (address tokenA, address tokenB)
Definition at line 332 of file FlashLiquidator.sol.
References token1(), and uint256.
Referenced by pancakeCall().
pancakeCall()
function pancakeCall (address sender, uint256 amount0, uint256 amount1, bytes calldata data)
Definition at line 192 of file FlashLiquidator.sol.
References dai, daiJoin, executeClipperLiquidation(), FlashLoanData::expectedCollateral, FlashLiquidation(), flashLoanState, FlashLoanData::inFlashLoan, pairFor(), router, token1(), uint256, and WBNB.
rely()
function rely (address usr)
Definition at line 62 of file FlashLiquidator.sol.
References usr.
removeCollateral()
function removeCollateral (address token)
Definition at line 118 of file FlashLiquidator.sol.
swap()
function swap (uint amount0Out, uint amount1Out, address to, bytes calldata data)
swapExactTokensForTokens()
function swapExactTokensForTokens (uint256 amountIn, uint256 amountOutMin, address[]calldata path, address to, uint256 deadline)
token1()
function token1 ()
Referenced by liquidateMemeCollateral(), pairFor(), and pancakeCall().
transfer()
function transfer (address recipient, uint256 amount)
Definition at line 40 of file MockToken.sol.
References transferFrom().
transferFrom()
function transferFrom (address sender, address recipient, uint256 amount)
Definition at line 44 of file MockToken.sol.
References add(), allowance(), balanceOf(), max(), sub(), Transfer(), type, and uint256.
Variable Documentation
_
_
Definition at line 64 of file FlashLiquidator.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "FlashLiquidator/not-authorized")
Definition at line 64 of file FlashLiquidator.sol.
blockTimestampLast
function uint112 uint32 blockTimestampLast
Definition at line 50 of file FlashLiquidator.sol.
dai
immutable dai
Definition at line 69 of file FlashLiquidator.sol.
Referenced by clipperCall(), constructor(), constructor(), exit(), fold(), frob(), getWBNBForDAI(), heal(), liquidateMemeCollateral(), move(), pancakeCall(), and suck().
daiJoin
immutable daiJoin
Definition at line 68 of file FlashLiquidator.sol.
Referenced by constructor(), and pancakeCall().
FlashLiquidator
contract FlashLiquidator
Initial value:
{
    using DSMath for uint256
Definition at line 57 of file FlashLiquidator.sol.
flashLoanState
struct FlashLoanData flashLoanState
Referenced by clipperCall(), getFlashLoanState(), liquidateMemeCollateral(), and pancakeCall().
isViable
isViable
Initial value:
{
        estimatedProfit = repayAmount / 20
Definition at line 348 of file FlashLiquidator.sol.
reserve1
function uint112 reserve1
Definition at line 50 of file FlashLiquidator.sol.
router
constant router = IPancakeRouter(0x10ED43C718714eb63d5aA57B78B54704E256024E)
Definition at line 72 of file FlashLiquidator.sol.
Referenced by clipperCall(), getWBNBForDAI(), and pancakeCall().
solidity
pragma solidity
Definition at line 2 of file FlashLiquidator.sol.
vat
immutable vat
Definition at line 67 of file FlashLiquidator.sol.
WBNB
constant WBNB = 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
Definition at line 73 of file FlashLiquidator.sol.
Referenced by clipperCall(), getWBNBForDAI(), liquidateMemeCollateral(), and pancakeCall().