USDog Stablecoin Protocol: Join.sol File Reference
Join.sol File Reference
import "./lib/DSMath.sol";
Functions
function move (address, address, uint256) external
function transfer (address, uint256) external returns(bool)
function transferFrom (address, address, uint256) external returns(bool)
function balanceOf (address) external view returns(uint256)
function burn (address, uint256) external
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
constructor (address vat_, bytes32 ilk_, address gem_)
function cage () external auth
function join (address usr, uint256 wad) external
function exit (address usr, uint256 wad) external
constructor (address vat_, address dai_)
Variables
pragma solidity
contract GemJoin
modifier auth { require(wards[msg.sender] == 1, "GemJoin/not-authorized")
_
vat
ilk
gem
dec
live
contract DaiJoin
dai
uint256 constant ONE = 10 ** 27
Function Documentation
balanceOf()
function balanceOf (address)
References burn(), mint(), and uint256.
burn()
function burn (address usr, uint256 wad)
Definition at line 90 of file StableCoin.sol.
References allowance(), balanceOf(), max(), sub(), totalSupply, Transfer(), type, uint256, and usr.
Referenced by balanceOf().
cage()
function cage ()
Definition at line 49 of file Join.sol.
References live.
constructor() [1/2]
constructor (address vat_, address dai_)
Definition at line 84 of file Join.sol.
References dai, live, and vat.
constructor() [2/2]
constructor (address vat_, bytes32 ilk_, address gem_)
Definition at line 40 of file Join.sol.
References dec, gem, ilk, live, and vat.
deny()
function deny (address usr)
Definition at line 31 of file Join.sol.
References usr.
exit()
function exit (address usr, uint256 wad)
Definition at line 61 of file Join.sol.
References dai, dec, gem, ilk, live, ONE, uint256, usr, and vat.
join()
function join (address usr, uint256 wad)
Definition at line 53 of file Join.sol.
References dec, gem, ilk, live, uint256, usr, and vat.
Referenced by addCollateral().
mapping()
mapping (address , uint256)
move()
function move (address src, address dst, uint256 rad)
Definition at line 133 of file Vat.sol.
rely()
function rely (address usr)
Definition at line 30 of file Join.sol.
References usr.
transfer()
function transfer (address dst, uint256 wad)
Definition at line 40 of file MockToken.sol.
References transferFrom().
transferFrom()
function transferFrom (address src, address dst, uint256 wad)
Definition at line 44 of file MockToken.sol.
References add(), allowance(), balanceOf(), max(), sub(), Transfer(), type, and uint256.
Referenced by transfer(), and transfer().
Variable Documentation
_
_
Definition at line 32 of file Join.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "GemJoin/not-authorized")
Definition at line 32 of file Join.sol.
dai
dai
Definition at line 81 of file Join.sol.
DaiJoin
contract DaiJoin
Initial value:
{
    using DSMath for uint256
Definition at line 71 of file Join.sol.
Referenced by DocsPage().
dec
dec
Definition at line 37 of file Join.sol.
Referenced by constructor(), exit(), and join().
gem
gem
Definition at line 36 of file Join.sol.
Referenced by constructor(), exit(), flux(), frob(), grab(), join(), and slip().
GemJoin
contract GemJoin
Initial value:
{
    using DSMath for uint256
Definition at line 25 of file Join.sol.
Referenced by DocsPage().
ilk
ilk
Definition at line 35 of file Join.sol.
live
live
Definition at line 38 of file Join.sol.
ONE
uint256 constant ONE = 10 ** 27
Definition at line 95 of file Join.sol.
Referenced by exit().
solidity
pragma solidity
Definition at line 2 of file Join.sol.
vat
vat
Definition at line 34 of file Join.sol.