USDog Stablecoin Protocol: Jug.sol File Reference
Jug.sol File Reference
import "./lib/DSMath.sol";
Data Structures
struct Ilk
Functions
function fold (bytes32, address, int256) external
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
struct Ilk mapping (bytes32=> Ilk) public ilks
event Init (bytes32 indexed ilk)
event File (bytes32 indexed what, uint256 data)
event File (bytes32 indexed ilk, bytes32 indexed what, uint256 data)
event File (bytes32 indexed what, address data)
event Drip (bytes32 indexed ilk, uint256 rate)
constructor (address vat_)
function rpow (uint256 x, uint256 n, uint256 base_) internal pure returns(uint256 z)
function init (bytes32 ilk) external auth
function file (bytes32 what, uint256 data) external auth
function file (bytes32 ilk, bytes32 what, uint256 data) external auth
function file (bytes32 what, address data) external auth
function cage () external auth
function drip (bytes32 ilk) external returns(uint256 rate)
function rho (bytes32 ilk) external view returns(uint256)
function duty (bytes32 ilk) external view returns(uint256)
Variables
pragma solidity
contract Jug
modifier auth { require(wards[msg.sender] == 1, "Jug/not-authorized")
_
uint256 duty
uint256 rho
vat
vow
base
live
Function Documentation
cage()
function cage ()
Definition at line 105 of file Jug.sol.
References live.
constructor()
constructor (address vat_)
Definition at line 45 of file Jug.sol.
References live, and vat.
deny()
function deny (address usr)
Definition at line 21 of file Jug.sol.
References usr.
drip()
function drip (bytes32 ilk)
Definition at line 110 of file Jug.sol.
References base, Drip(), DSMath, ilk, ilks(), rpow(), uint256, vat, and vow.
Drip()
event Drip (bytes32 indexed ilk, uint256 rate)
Referenced by drip().
duty()
function duty (bytes32 ilk)
Definition at line 124 of file Jug.sol.
References ilk, and ilks().
file() [1/3]
function file (bytes32 ilk, bytes32 what, uint256 data)
Definition at line 91 of file Jug.sol.
References File(), ilk, ilks(), and live.
File() [1/3]
event File (bytes32 indexed ilk, bytes32 indexed what, uint256 data)
File() [2/3]
event File (bytes32 indexed what, address data)
File() [3/3]
event File (bytes32 indexed what, uint256 data)
Referenced by file(), file(), and file().
file() [2/3]
function file (bytes32 what, address data)
Definition at line 98 of file Jug.sol.
References File(), live, and vow.
file() [3/3]
function file (bytes32 what, uint256 data)
Definition at line 84 of file Jug.sol.
References base, File(), and live.
fold()
function fold (bytes32 i, address u, int256 rate)
Definition at line 190 of file Vat.sol.
References _addInt(), _mulInt(), dai, debt, ilk, ilks(), live, and Ilk::rate.
init()
function init (bytes32 ilk)
Definition at line 77 of file Jug.sol.
References ilk, ilks(), and Init().
Init()
event Init (bytes32 indexed ilk)
Referenced by init().
mapping() [1/2]
mapping (address , uint256)
mapping() [2/2]
struct Ilk mapping (bytes32 , Ilk)
rely()
function rely (address usr)
Definition at line 20 of file Jug.sol.
References usr.
rho()
function rho (bytes32 ilk)
Definition at line 120 of file Jug.sol.
References ilk, and ilks().
rpow()
function rpow (uint256 x, uint256 n, uint256 base_)
Definition at line 52 of file Jug.sol.
References add(), and mul().
Referenced by drip().
Variable Documentation
_
_
Definition at line 22 of file Jug.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "Jug/not-authorized")
Definition at line 22 of file Jug.sol.
base
base
Definition at line 33 of file Jug.sol.
Referenced by drip(), file(), and rpow().
duty
uint256 duty
Definition at line 0 of file Jug.sol.
Referenced by DocsPage().
Jug
contract Jug
Initial value:
{
    using DSMath for uint256
Definition at line 15 of file Jug.sol.
Referenced by DocsPage().
live
live
Definition at line 35 of file Jug.sol.
Referenced by cage(), constructor(), file(), file(), and file().
rho
uint256 rho
Definition at line 1 of file Jug.sol.
solidity
pragma solidity
Definition at line 2 of file Jug.sol.
vat
vat
Definition at line 31 of file Jug.sol.
Referenced by constructor(), and drip().
vow
vow
Definition at line 32 of file Jug.sol.
Referenced by drip(), and file().