USDog Stablecoin Protocol: MockToken.sol File Reference
MockToken.sol File Reference
Functions
mapping (address=> uint256) public balanceOf
mapping (address=> mapping(address=> uint256)) public allowance
event Approval (address indexed src, address indexed guy, uint256 wad)
event Transfer (address indexed src, address indexed dst, uint256 wad)
constructor (string memory name_, string memory symbol_, uint256 totalSupply_)
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function transfer (address dst, uint256 wad) external returns(bool)
function transferFrom (address src, address dst, uint256 wad) public returns(bool)
function approve (address usr, uint256 wad) external returns(bool)
function mint (address usr, uint256 wad) external
Variables
pragma solidity
contract MockToken
symbol
constant decimals = 18
totalSupply
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 31 of file MockToken.sol.
Referenced by mint(), and transferFrom().
Approval()
event Approval (address indexed src, address indexed guy, uint256 wad)
Referenced by approve().
approve()
function approve (address usr, uint256 wad)
Definition at line 59 of file MockToken.sol.
constructor()
constructor (string memory name_, string memory symbol_, uint256 totalSupply_)
Definition at line 22 of file MockToken.sol.
References balanceOf(), name, symbol, totalSupply, and Transfer().
mapping() [1/2]
mapping (address , mapping(address=> uint256))
mapping() [2/2]
mapping (address , uint256)
mint()
function mint (address usr, uint256 wad)
Definition at line 66 of file MockToken.sol.
References add(), balanceOf(), totalSupply, Transfer(), and usr.
Referenced by balanceOf(), and DocsPage().
sub()
function sub (uint256 x, uint256 y)
Definition at line 35 of file MockToken.sol.
Referenced by transferFrom().
transfer()
function transfer (address dst, uint256 wad)
Definition at line 40 of file MockToken.sol.
Transfer()
event Transfer (address indexed src, address indexed dst, uint256 wad)
Referenced by constructor(), mint(), and transferFrom().
transferFrom()
function transferFrom (address src, address dst, uint256 wad)
Definition at line 44 of file MockToken.sol.
Referenced by transfer().
Variable Documentation
decimals
constant decimals = 18
Definition at line 12 of file MockToken.sol.
Referenced by useStablecoin().
MockToken
contract MockToken
Initial value:
{
    string  public name
Definition at line 7 of file MockToken.sol.
solidity
pragma solidity
Definition at line 2 of file MockToken.sol.
symbol
symbol
Definition at line 11 of file MockToken.sol.
Referenced by constructor().
totalSupply
totalSupply
Definition at line 13 of file MockToken.sol.
Referenced by constructor(), and mint().