USDog Stablecoin Protocol: Pot.sol File Reference
Pot.sol File Reference
import "./lib/DSMath.sol";
Functions
function suck (address, address, uint256) external
mapping (address=> uint256) public wards
function rely (address guy) external auth
function deny (address guy) external auth
event Join (address indexed usr, uint256 wad)
event Exit (address indexed usr, uint256 wad)
event Drip (uint256 tmp)
event File (bytes32 indexed what, uint256 data)
event File (bytes32 indexed what, address addr)
event Cage ()
constructor (address vat_)
function rpow (uint256 x, uint256 n, uint256 base) internal pure returns(uint256 z)
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function mul (uint256 x, uint256 y) internal pure returns(uint256 z)
function file (bytes32 what, uint256 data) external auth
function file (bytes32 what, address addr) external auth
function cage () external auth
function drip () external returns(uint256 tmp)
function join (uint256 wad) external
function exit (uint256 wad) external
Variables
pragma solidity
contract Pot
modifier auth { require(wards[msg.sender] == 1, "Pot/not-authorized")
_
Pie
dsr
chi
vat
vow
rho
live
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 82 of file Pot.sol.
Referenced by join(), and rpow().
Cage()
event Cage ()
Referenced by cage().
cage()
function cage ()
Definition at line 107 of file Pot.sol.
References Cage(), DSMath, dsr, and live.
constructor()
constructor (address vat_)
Definition at line 48 of file Pot.sol.
References chi, DSMath, dsr, live, rho, and vat.
deny()
function deny (address guy)
Definition at line 23 of file Pot.sol.
drip()
function drip ()
Definition at line 114 of file Pot.sol.
References chi, Drip(), DSMath, dsr, mul(), Pie, rho, rpow(), sub(), uint256, vat, and vow.
Drip()
event Drip (uint256 tmp)
Referenced by drip().
Exit()
event Exit (address indexed usr, uint256 wad)
Referenced by exit().
exit()
function exit (uint256 wad)
Definition at line 134 of file Pot.sol.
References chi, Exit(), mul(), Pie, sub(), and vat.
File() [1/2]
event File (bytes32 indexed what, address addr)
File() [2/2]
event File (bytes32 indexed what, uint256 data)
Referenced by file(), and file().
file() [1/2]
function file (bytes32 what, address addr)
Definition at line 100 of file Pot.sol.
References File(), live, and vow.
file() [2/2]
function file (bytes32 what, uint256 data)
Definition at line 93 of file Pot.sol.
References dsr, File(), and live.
Join()
event Join (address indexed usr, uint256 wad)
Referenced by DocsPage(), and join().
join()
function join (uint256 wad)
Definition at line 125 of file Pot.sol.
References add(), chi, Join(), mul(), Pie, rho, and vat.
mapping()
mapping (address , uint256)
mul()
function mul (uint256 x, uint256 y)
Definition at line 88 of file Pot.sol.
Referenced by drip(), exit(), join(), and rpow().
rely()
function rely (address guy)
Definition at line 22 of file Pot.sol.
rpow()
function rpow (uint256 x, uint256 n, uint256 base)
Definition at line 58 of file Pot.sol.
References add(), base, and mul().
Referenced by drip().
sub()
function sub (uint256 x, uint256 y)
Definition at line 85 of file Pot.sol.
Referenced by drip(), and exit().
suck()
function suck (address u, address v, uint256 rad)
Definition at line 226 of file Vat.sol.
Variable Documentation
_
_
Definition at line 24 of file Pot.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "Pot/not-authorized")
Definition at line 24 of file Pot.sol.
chi
chi
Definition at line 31 of file Pot.sol.
Referenced by constructor(), drip(), exit(), and join().
dsr
dsr
Definition at line 30 of file Pot.sol.
Referenced by cage(), constructor(), drip(), and file().
live
live
Definition at line 37 of file Pot.sol.
Referenced by cage(), constructor(), file(), and file().
Pie
Pie
Definition at line 29 of file Pot.sol.
Referenced by drip(), exit(), and join().
Pot
contract Pot
Initial value:
{
    using DSMath for uint256
Definition at line 17 of file Pot.sol.
Referenced by DocsPage().
rho
rho
Definition at line 35 of file Pot.sol.
Referenced by constructor(), drip(), and join().
solidity
pragma solidity
Definition at line 2 of file Pot.sol.
vat
vat
Definition at line 33 of file Pot.sol.
Referenced by constructor(), drip(), exit(), and join().
vow
vow
Definition at line 34 of file Pot.sol.
Referenced by drip(), and file().