USDog Stablecoin Protocol: PriceFeed.sol File Reference
PriceFeed.sol File Reference
import "./lib/DSMath.sol";
import "@api3/contracts/interfaces/IApi3ReaderProxy.sol";
Functions
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
event LogValue (bytes32 val)
constructor ()
function peek () public view returns(bytes32
function read () external view returns(bytes32)
function poke (uint128 wut) external auth
function void () external auth
function decimals () external view returns(uint8)
constructor (address _priceFeed)
function setStalePeriod (uint256 _stalePeriod) external auth
Variables
pragma solidity
contract PriceFeed
modifier auth { require(wards[msg.sender] == 1, "PriceFeed/not-authorized")
_
val
zzz
function bool
contract ChainlinkPriceFeed
AggregatorV3Interface internal priceFeed
feedDecimals
stalePeriod
contract Api3PriceFeed
Function Documentation
constructor() [1/2]
constructor ()
Definition at line 25 of file PriceFeed.sol.
constructor() [2/2]
constructor (address _priceFeed)
Definition at line 83 of file PriceFeed.sol.
References feedDecimals, priceFeed, and stalePeriod.
decimals()
function decimals ()
Definition at line 12 of file MockToken.sol.
Referenced by useStablecoin().
deny()
function deny (address usr)
Definition at line 15 of file PriceFeed.sol.
References usr.
LogValue()
event LogValue (bytes32 val)
Referenced by poke(), and void().
mapping()
mapping (address , uint256)
peek()
function peek ()
Referenced by read().
poke()
function poke (uint128 wut)
Definition at line 42 of file PriceFeed.sol.
References LogValue(), uint256, val, and zzz.
read()
function read ()
Definition at line 34 of file PriceFeed.sol.
References peek().
rely()
function rely (address usr)
Definition at line 14 of file PriceFeed.sol.
References usr.
setStalePeriod()
function setStalePeriod (uint256 _stalePeriod)
Definition at line 90 of file PriceFeed.sol.
References stalePeriod.
void()
function void ()
Definition at line 48 of file PriceFeed.sol.
References LogValue(), val, and zzz.
Variable Documentation
_
_
Definition at line 16 of file PriceFeed.sol.
Api3PriceFeed
contract Api3PriceFeed
Initial value:
{
    mapping (address => uint256) public wards
Definition at line 131 of file PriceFeed.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "PriceFeed/not-authorized")
Definition at line 16 of file PriceFeed.sol.
bool
function bool
Initial value:
{
        return (bytes32(uint256(val)), val > 0)
Definition at line 30 of file PriceFeed.sol.
ChainlinkPriceFeed
contract ChainlinkPriceFeed
Initial value:
{
    mapping (address => uint256) public wards
Definition at line 71 of file PriceFeed.sol.
feedDecimals
feedDecimals
Definition at line 80 of file PriceFeed.sol.
Referenced by constructor().
PriceFeed
contract PriceFeed
Initial value:
{
    using DSMath for uint256
Definition at line 9 of file PriceFeed.sol.
Referenced by DocsPage().
priceFeed
IApi3ReaderProxy internal priceFeed
Definition at line 79 of file PriceFeed.sol.
Referenced by constructor().
solidity
pragma solidity
Definition at line 2 of file PriceFeed.sol.
stalePeriod
stalePeriod
Definition at line 81 of file PriceFeed.sol.
Referenced by constructor(), and setStalePeriod().
val
val
Definition at line 19 of file PriceFeed.sol.
Referenced by poke(), poke(), and void().
zzz
zzz
Definition at line 20 of file PriceFeed.sol.
Referenced by poke(), and void().