USDog Stablecoin Protocol: Spot.sol File Reference
Spot.sol File Reference
import "./lib/DSMath.sol";
Data Structures
struct Ilk
Functions
mapping (address=> uint256) public wards
function rely (address guy) external auth
function deny (address guy) external auth
struct Ilk mapping (bytes32=> Ilk) public ilks
event Poke (bytes32 indexed ilk, bytes32 indexed val, uint256 indexed spot)
constructor (address vat_)
function mul (uint256 x, uint256 y) internal pure returns(uint256 z)
function rdiv (uint256 x, uint256 y) internal pure returns(uint256 z)
function file (bytes32 what, uint256 data) external auth
function file (bytes32 ilk, bytes32 what, uint256 data) external auth
function file (bytes32 ilk, bytes32 what, address pip_) external auth
function cage () external auth
function poke (bytes32 ilk) external
Variables
pragma solidity
contract Spot
modifier auth { require(wards[msg.sender] == 1, "Spot/not-authorized")
_
PipLike pip
uint256 mat
vat
par
live
Function Documentation
cage()
function cage ()
Definition at line 81 of file Spot.sol.
References live.
constructor()
constructor (address vat_)
Definition at line 47 of file Spot.sol.
References DSMath, live, par, and vat.
deny()
function deny (address guy)
Definition at line 24 of file Spot.sol.
file() [1/3]
function file (bytes32 ilk, bytes32 what, address pip_)
Definition at line 75 of file Spot.sol.
References ilk, ilks(), and live.
file() [2/3]
function file (bytes32 ilk, bytes32 what, uint256 data)
Definition at line 69 of file Spot.sol.
References ilk, ilks(), and live.
file() [3/3]
function file (bytes32 what, uint256 data)
Definition at line 63 of file Spot.sol.
References live, and par.
mapping() [1/2]
mapping (address , uint256)
mapping() [2/2]
struct Ilk mapping (bytes32 , Ilk)
mul()
function mul (uint256 x, uint256 y)
Definition at line 55 of file Spot.sol.
poke()
function poke (bytes32 ilk)
Definition at line 86 of file Spot.sol.
References ilk, ilks(), mat, mul(), par, pip, Poke(), rdiv(), spot, uint256, val, and vat.
Poke()
event Poke (bytes32 indexed ilk, bytes32 indexed val, uint256 indexed spot)
Referenced by poke().
rdiv()
function rdiv (uint256 x, uint256 y)
Definition at line 58 of file Spot.sol.
References DSMath, and mul().
rely()
function rely (address guy)
Definition at line 23 of file Spot.sol.
Variable Documentation
_
_
Definition at line 25 of file Spot.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "Spot/not-authorized")
Definition at line 25 of file Spot.sol.
live
live
Definition at line 37 of file Spot.sol.
mat
uint256 mat
Definition at line 1 of file Spot.sol.
Referenced by DocsPage(), and poke().
par
par
Definition at line 36 of file Spot.sol.
Referenced by constructor(), file(), and poke().
pip
PipLike pip
Definition at line 0 of file Spot.sol.
Referenced by DocsPage(), and poke().
solidity
pragma solidity
Definition at line 2 of file Spot.sol.
Spot
contract Spot
Initial value:
{
    using DSMath for uint256
Definition at line 18 of file Spot.sol.
Referenced by DocsPage().
vat
vat
Definition at line 35 of file Spot.sol.