USDog Stablecoin Protocol: StableCoin.sol File Reference
StableCoin.sol File Reference
Functions
function rely (address guy) external auth
function deny (address guy) external auth
mapping (address=> uint256) public balanceOf
mapping (address=> mapping(address=> uint256)) public allowance
event Approval (address indexed src, address indexed guy, uint256 wad)
event Transfer (address indexed src, address indexed dst, uint256 wad)
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
constructor (uint256 chainId_)
function transfer (address dst, uint256 wad) external returns(bool)
function transferFrom (address src, address dst, uint256 wad) public returns(bool)
function approve (address usr, uint256 wad) external returns(bool)
function mint (address usr, uint256 wad) external auth
function burn (address usr, uint256 wad) external
function permit (address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s) external
Variables
pragma solidity
contract StableCoin
modifier auth { require(wards[msg.sender] == 1, "StableCoin/not-authorized")
_
constant name = "USDog"
constant symbol = "USDog"
constant version = "1"
constant decimals = 18
totalSupply
DOMAIN_SEPARATOR
constant PERMIT_TYPEHASH = keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)")
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 34 of file StableCoin.sol.
Referenced by mint(), and transferFrom().
Approval()
event Approval (address indexed src, address indexed guy, uint256 wad)
Referenced by approve(), and permit().
approve()
function approve (address usr, uint256 wad)
Definition at line 77 of file StableCoin.sol.
References allowance(), Approval(), and usr.
burn()
function burn (address usr, uint256 wad)
Definition at line 90 of file StableCoin.sol.
References allowance(), balanceOf(), max(), sub(), totalSupply, Transfer(), type, uint256, and usr.
Referenced by balanceOf().
constructor()
constructor (uint256 chainId_)
Definition at line 46 of file StableCoin.sol.
References DOMAIN_SEPARATOR, name, and version.
deny()
function deny (address guy)
Definition at line 15 of file StableCoin.sol.
mapping() [1/2]
mapping (address , mapping(address=> uint256))
mapping() [2/2]
mapping (address , uint256)
mint()
function mint (address usr, uint256 wad)
Definition at line 84 of file StableCoin.sol.
References add(), balanceOf(), totalSupply, Transfer(), and usr.
permit()
function permit (address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)
Definition at line 104 of file StableCoin.sol.
References allowance(), Approval(), DOMAIN_SEPARATOR, and PERMIT_TYPEHASH.
rely()
function rely (address guy)
Definition at line 14 of file StableCoin.sol.
sub()
function sub (uint256 x, uint256 y)
Definition at line 38 of file StableCoin.sol.
Referenced by burn(), and transferFrom().
transfer()
function transfer (address dst, uint256 wad)
Definition at line 58 of file StableCoin.sol.
References transferFrom().
Transfer()
event Transfer (address indexed src, address indexed dst, uint256 wad)
Referenced by burn(), mint(), and transferFrom().
transferFrom()
function transferFrom (address src, address dst, uint256 wad)
Definition at line 62 of file StableCoin.sol.
References add(), allowance(), balanceOf(), max(), sub(), Transfer(), type, and uint256.
Referenced by transfer().
Variable Documentation
_
_
Definition at line 16 of file StableCoin.sol.
auth
modifier auth { require(wards[msg.sender] == 1, "StableCoin/not-authorized")
Definition at line 16 of file StableCoin.sol.
decimals
constant decimals = 18
Definition at line 22 of file StableCoin.sol.
DOMAIN_SEPARATOR
DOMAIN_SEPARATOR
Definition at line 43 of file StableCoin.sol.
Referenced by constructor(), and permit().
name
constant name = "USDog"
Definition at line 19 of file StableCoin.sol.
Referenced by constructor(), constructor(), and useStablecoin().
PERMIT_TYPEHASH
constant PERMIT_TYPEHASH = keccak256("Permit(address owner,address spender,uint256 value,uint256 nonce,uint256 deadline)")
Definition at line 44 of file StableCoin.sol.
Referenced by permit().
solidity
pragma solidity
Definition at line 2 of file StableCoin.sol.
StableCoin
contract StableCoin
Initial value:
{
    mapping (address => uint256) public wards
Definition at line 10 of file StableCoin.sol.
Referenced by DocsPage().
symbol
constant symbol = "USDog"
Definition at line 20 of file StableCoin.sol.
totalSupply
totalSupply
Definition at line 23 of file StableCoin.sol.
Referenced by burn(), and mint().
version
constant version = "1"
Definition at line 21 of file StableCoin.sol.
Referenced by constructor().