USDog Stablecoin Protocol: Vat.sol File Reference
Vat.sol File Reference
import "./lib/DSMath.sol";
Data Structures
struct Ilk
Functions
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
mapping (bytes32=> Ilk) public ilks
mapping (bytes32=> mapping(address=> Urn)) public urns
mapping (bytes32=> mapping(address=> uint256)) public gem
event LogNote (bytes4 indexed sig, address indexed usr, bytes32 indexed arg1, bytes32 indexed arg2, bytes data) anonymous
emit LogNote (msg.sig, msg.sender, 0, 0, msg.data)
constructor ()
function _add (uint256 x, uint256 y) internal pure returns(uint256 z)
function _sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function _mul (uint256 x, uint256 y) internal pure returns(uint256 z)
function _addInt (uint256 x, int256 y) internal pure returns(uint256 z)
function _mulInt (uint256 x, int256 y) internal pure returns(int256 z)
function init (bytes32 ilk) external auth
function file (bytes32 what, uint256 data) external auth
function file (bytes32 ilk, bytes32 what, uint256 data) external auth
function cage () external auth
function slip (bytes32 ilk, address usr, int256 wad) external auth
function flux (bytes32 ilk, address src, address dst, uint256 wad) external
function move (address src, address dst, uint256 rad) external
function wish (address bit, address usr) internal view returns(bool)
function either (bool x, bool y) internal pure returns(bool z)
function frob (bytes32 i, address u, address v, address w, int256 dink, int256 dart) external
function fold (bytes32 i, address u, int256 rate) external auth
function grab (bytes32 i, address u, address v, address w, int256 dink, int256 dart) external auth
function heal (uint256 rad) external
function suck (address u, address v, uint256 rad) external auth
mapping (address=> mapping(address=> uint256)) public can
function hope (address usr) external
function nope (address usr) external
function both (bool x, bool y) internal pure returns(bool z)
Variables
pragma solidity
contract Vat
modifier auth { require(wards[msg.sender] == 1, "Vat/not-authorized")
_
struct Ilk ink
uint256 art
debt
vice
Line
live
modifier note
Function Documentation
_add()
function _add (uint256 x, uint256 y)
Definition at line 74 of file Vat.sol.
Referenced by _addInt(), flux(), move(), and suck().
_addInt()
function _addInt (uint256 x, int256 y)
Definition at line 87 of file Vat.sol.
References _add(), _sub(), and uint256.
Referenced by fold(), frob(), grab(), and slip().
_mul()
function _mul (uint256 x, uint256 y)
Definition at line 82 of file Vat.sol.
Referenced by _mulInt(), and frob().
_mulInt()
function _mulInt (uint256 x, int256 y)
Definition at line 92 of file Vat.sol.
References _mul(), and uint256.
Referenced by fold(), frob(), and grab().
_sub()
function _sub (uint256 x, uint256 y)
Definition at line 78 of file Vat.sol.
Referenced by _addInt(), flux(), heal(), and move().
both()
function both (bool x, bool y)
Definition at line 240 of file Vat.sol.
Referenced by frob().
cage()
function cage ()
Definition at line 117 of file Vat.sol.
References live.
constructor()
constructor ()
Definition at line 67 of file Vat.sol.
References live.
deny()
function deny (address usr)
Definition at line 19 of file Vat.sol.
References usr.
either()
function either (bool x, bool y)
Definition at line 143 of file Vat.sol.
Referenced by frob(), and wish().
file() [1/2]
function file (bytes32 ilk, bytes32 what, uint256 data)
Definition at line 109 of file Vat.sol.
References ilk, ilks(), and live.
file() [2/2]
function file (bytes32 what, uint256 data)
Definition at line 103 of file Vat.sol.
References Line, and live.
flux()
function flux (bytes32 ilk, address src, address dst, uint256 wad)
Definition at line 127 of file Vat.sol.
References _add(), _sub(), gem, ilk, and wish().
fold()
function fold (bytes32 i, address u, int256 rate)
Definition at line 190 of file Vat.sol.
References _addInt(), _mulInt(), dai, debt, ilk, ilks(), live, and Ilk::rate.
frob()
function frob (bytes32 i, address u, address v, address w, int256 dink, int256 dart)
Definition at line 149 of file Vat.sol.
References _addInt(), _mul(), _mulInt(), both(), dai, debt, either(), gem, ilk, ilks(), Line, tab, uint256, urns(), and wish().
Referenced by DocsPage().
grab()
function grab (bytes32 i, address u, address v, address w, int256 dink, int256 dart)
Definition at line 201 of file Vat.sol.
References _addInt(), _mulInt(), gem, ilk, ilks(), sin(), urns(), and vice.
heal()
function heal (uint256 rad)
Definition at line 218 of file Vat.sol.
References _sub(), dai, debt, sin(), and vice.
hope()
function hope (address usr)
Definition at line 237 of file Vat.sol.
References usr.
init()
function init (bytes32 ilk)
Definition at line 98 of file Vat.sol.
References ilk, and ilks().
LogNote() [1/2]
event LogNote (bytes4 indexed sig, address indexed usr, bytes32 indexed arg1, bytes32 indexed arg2, bytes data)
LogNote() [2/2]
emit LogNote (msg. sig, msg. sender, 0 , 0 , msg. data)
mapping() [1/5]
mapping (address , mapping(address=> uint256))
mapping() [2/5]
mapping (address , uint256)
mapping() [3/5]
mapping (bytes32 , Ilk)
mapping() [4/5]
mapping (bytes32 , mapping(address=> uint256))
mapping() [5/5]
mapping (bytes32 , mapping(address=> Urn))
move()
function move (address src, address dst, uint256 rad)
Definition at line 133 of file Vat.sol.
References _add(), _sub(), dai, and wish().
Referenced by DocsPage().
nope()
function nope (address usr)
Definition at line 238 of file Vat.sol.
References usr.
rely()
function rely (address usr)
Definition at line 18 of file Vat.sol.
References usr.
slip()
function slip (bytes32 ilk, address usr, int256 wad)
Definition at line 123 of file Vat.sol.
References _addInt(), gem, ilk, and usr.
suck()
function suck (address u, address v, uint256 rad)
Definition at line 226 of file Vat.sol.
References _add(), dai, debt, sin(), and vice.
wish()
function wish (address bit, address usr)
Definition at line 139 of file Vat.sol.
References either(), and usr.
Referenced by flux(), frob(), and move().
Variable Documentation
_
_
Definition at line 20 of file Vat.sol.
art
uint256 art
Definition at line 36 of file Vat.sol.
Referenced by bark(), cage(), skim(), and useStablecoin().
auth
modifier auth { require(wards[msg.sender] == 1, "Vat/not-authorized")
Definition at line 20 of file Vat.sol.
debt
debt
Definition at line 45 of file Vat.sol.
Referenced by fold(), frob(), heal(), and suck().
ink
struct Ilk ink
Referenced by bark(), DocsPage(), free(), skim(), and useStablecoin().
Line
Line
Definition at line 47 of file Vat.sol.
Referenced by file(), and frob().
live
live
Definition at line 48 of file Vat.sol.
Referenced by cage(), constructor(), file(), file(), and fold().
note
modifier note
Initial value:
{
        _
Definition at line 60 of file Vat.sol.
solidity
pragma solidity
Definition at line 2 of file Vat.sol.
Vat
contract Vat
Initial value:
{
    using DSMath for uint256
Definition at line 13 of file Vat.sol.
Referenced by DocsPage(), and useStablecoin().
vice
vice
Definition at line 46 of file Vat.sol.
Referenced by grab(), heal(), and suck().