USDog Stablecoin Protocol: Vow.sol File Reference
Vow.sol File Reference
import "./lib/DSMath.sol";
Functions
function sin (address) external view returns(uint256)
function heal (uint256) external
function hope (address) external
function nope (address) external
function cage (uint256) external
function cage () external
function burn (address, uint256) external
mapping (address=> uint256) public wards
function rely (address usr) external auth
function deny (address usr) external auth
mapping (uint256=> uint256) public sin
event Fess (uint256 indexed era, uint256 tab)
event Flog (uint256 indexed era, uint256 tab)
event Heal (uint256 rad)
event Kiss (uint256 rad)
event Flop (uint256 indexed id, uint256 lot, uint256 bid)
event Flap (uint256 indexed id, uint256 lot, uint256 bid)
event Cage ()
constructor (address vat_, address flapper_, address flopper_)
function min (uint256 x, uint256 y) internal pure returns(uint256 z)
function add (uint256 x, uint256 y) internal pure returns(uint256 z)
function sub (uint256 x, uint256 y) internal pure returns(uint256 z)
function file (bytes32 what, uint256 data) external auth
function file (bytes32 what, address data) external auth
function fess (uint256 tab) external auth
function flog (uint256 era) external
function kiss (uint256 rad) external
function flop () external returns(uint256 id)
function flap () external returns(uint256 id)
Variables
pragma solidity
contract Vow
modifier auth { require(wards[msg.sender] == 1, "Vow/not-authorized")
_
vat
flapper
flopper
Sin
Ash
wait
dump
sump
bump
hump
live
Function Documentation
add()
function add (uint256 x, uint256 y)
Definition at line 88 of file Vow.sol.
burn()
function burn (address usr, uint256 wad)
Definition at line 90 of file StableCoin.sol.
Cage()
event Cage ()
cage() [1/2]
function cage ()
Definition at line 160 of file Vow.sol.
References Ash, Cage(), flapper, flopper, live, Sin, and vat.
cage() [2/2]
function cage (uint256 amount)
Definition at line 9 of file MockAuctions.sol.
constructor()
constructor (address vat_, address flapper_, address flopper_)
Definition at line 75 of file Vow.sol.
References flapper, flopper, live, and vat.
deny()
function deny (address usr)
Definition at line 44 of file Vow.sol.
References usr.
Fess()
event Fess (uint256 indexed era, uint256 tab)
Referenced by fess().
fess()
function fess (uint256 tab)
Definition at line 116 of file Vow.sol.
References add(), Fess(), sin(), Sin, and tab.
file() [1/2]
function file (bytes32 what, address data)
Definition at line 105 of file Vow.sol.
References flapper, flopper, and vat.
file() [2/2]
function file (bytes32 what, uint256 data)
Definition at line 96 of file Vow.sol.
References bump, dump, hump, sump, and wait.
flap()
function flap ()
Definition at line 153 of file Vow.sol.
References add(), Ash, bump, Flap(), flapper, Sin, sub(), and vat.
Flap()
event Flap (uint256 indexed id, uint256 lot, uint256 bid)
Referenced by DocsPage(), and flap().
flog()
function flog (uint256 era)
Definition at line 122 of file Vow.sol.
References add(), Flog(), sin(), Sin, sub(), and wait.
Flog()
event Flog (uint256 indexed era, uint256 tab)
Referenced by flog().
flop()
function flop ()
Definition at line 145 of file Vow.sol.
References add(), Ash, dump, Flop(), flopper, Sin, sub(), sump, and vat.
Flop()
event Flop (uint256 indexed id, uint256 lot, uint256 bid)
Referenced by DocsPage(), and flop().
Heal()
event Heal (uint256 rad)
Referenced by heal().
heal()
function heal (uint256 rad)
Definition at line 129 of file Vow.sol.
References Ash, Heal(), Sin, sub(), and vat.
hope()
function hope (address usr)
Definition at line 237 of file Vat.sol.
Kiss()
event Kiss (uint256 rad)
Referenced by kiss().
kiss()
function kiss (uint256 rad)
Definition at line 136 of file Vow.sol.
References Ash, Kiss(), sub(), and vat.
mapping() [1/2]
mapping (address , uint256)
mapping() [2/2]
mapping (uint256 , uint256)
min()
function min (uint256 x, uint256 y)
Definition at line 85 of file Vow.sol.
nope()
function nope (address usr)
Definition at line 238 of file Vat.sol.
rely()
function rely (address usr)
Definition at line 43 of file Vow.sol.
References usr.
sin()
function sin (address)
Referenced by fess(), flog(), grab(), heal(), and suck().
sub()
function sub (uint256 x, uint256 y)
Definition at line 91 of file Vow.sol.
Variable Documentation
_
_
Definition at line 45 of file Vow.sol.
Ash
Ash
Definition at line 54 of file Vow.sol.
Referenced by cage(), flap(), flop(), heal(), and kiss().
auth
modifier auth { require(wards[msg.sender] == 1, "Vow/not-authorized")
Definition at line 45 of file Vow.sol.
bump
bump
Definition at line 60 of file Vow.sol.
Referenced by file(), and flap().
dump
dump
Definition at line 57 of file Vow.sol.
Referenced by file(), and flop().
flapper
flapper
Definition at line 49 of file Vow.sol.
Referenced by cage(), constructor(), file(), and flap().
flopper
flopper
Definition at line 50 of file Vow.sol.
Referenced by cage(), constructor(), file(), and flop().
hump
hump
Definition at line 61 of file Vow.sol.
Referenced by file().
live
live
Definition at line 63 of file Vow.sol.
Sin
Sin
Definition at line 53 of file Vow.sol.
Referenced by cage(), fess(), flap(), flog(), flop(), and heal().
solidity
pragma solidity
Definition at line 2 of file Vow.sol.
sump
sump
Definition at line 58 of file Vow.sol.
Referenced by file(), and flop().
vat
vat
Definition at line 48 of file Vow.sol.
Vow
contract Vow
Initial value:
{
    using DSMath for uint256
Definition at line 38 of file Vow.sol.
Referenced by DocsPage().
wait
wait
Definition at line 56 of file Vow.sol.