name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run Hardhat compile
        run: npx hardhat compile

      - name: Run tests
        run: npx hardhat test

      - name: Change to frontendnew
        run: cd frontendnew

      - name: Install frontend dependencies
        run: |
          cd frontendnew
          npm ci

      - name: Run frontend lint
        run: |
          cd frontendnew
          npm run lint

      - name: Run frontend build
        run: |
          cd frontendnew
          npm run build